### ISSUE TITLE
Missing dependency `pkg_resources` if installed without pip

### ISSUE THREAD

**Issue by skeapskeap** [bobthemighty/punq#183]
Hi.
I just noticed that punq doesn't depends on pkg_resources explicitly. The only thing that hints at this is recommended way of installation using pip.
```
(.venv) username:~$ python
Python 3.8.20 (default, Sep  9 2024, 22:12:42)
[Clang 18.1.8 ] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import punq
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/username/.venv/lib/python3.8/site-packages/punq/__init__.py", line 27, in <module>
    from pkg_resources import DistributionNotFound
ModuleNotFoundError: No module named 'pkg_resources'
```

**Comment by bobthemighty** [comment]
I think this may have been fixed by the toolchain refresh. Can you confirm on 0.7.1.dev1?

```
code/play/punq-test via 🐍 v3.12.6 (punq-test) on ☁️  (eu-west-2)
❯ pip install punq==0.7.1.dev1
Collecting punq==0.7.1.dev1
  Downloading punq-0.7.1.dev1-py3-none-any.whl.metadata (5.2 kB)
Downloading punq-0.7.1.dev1-py3-none-any.whl (13 kB)
Installing collected packages: punq
Successfully installed punq-0.7.1.dev1

code/play/punq-test via 🐍 v3.12.6 (punq-test) on ☁️  (eu-west-2)
❯ python
Python 3.12.6 (main, Sep  8 2024, 13:18:56) [GCC 14.2.1 20240805] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import punq
>>> punq
<module 'punq' from '/home/bob/.pyenv/versions/punq-test/lib/python3.12/site-packages/punq/__init__.py'>
>>> c.register("foo", instance="bar")
<punq.Container object at 0x7f242c11f950>
>>> c.resolve("foo")
'bar'
```
